#!/usr/bin/env sh

# Push docker image to heroku

cd "$(tem find -b veracioux-website)"

dgen

push() {
    heroku container:push --app veracioux -R web "$@"
    heroku container:push --app veracioux-worker-dotfiles -R worker_dotfiles "$@"
}

push || {
    heroku container:login
    push
}
