#!/usr/bin/env sh

# Release docker image on heroku

cd "$(tem find -b veracioux-website)"

release() {
    heroku container:release --app veracioux web "$@"
    heroku container:release --app veracioux-worker-dotfiles worker_dotfiles "$@"
}

release || {
    heroku container:login
    release
}
