#!/usr/bin/env sh

# Verify that the website URLs work

set -e

{
    curl veracioux.me
    curl www.veracioux.me/status
    curl http://veracioux.me/status
    curl http://www.veracioux.me/status
    curl http://api.veracioux.me/status
    curl http://worker.veracioux.me/status
} 2>&1 >/dev/null
