version: '3.4'

services:
  db:
    image: postgres:14.1-alpine
    container_name: veracioux-db
    ports: ["5432:5432"]
    env_file: &env_file
      - ./.env/common
      - ./.env/prod
      - ./.env/prod.secret
      - worker/.env/common
      - worker/.env/prod.secret

  rabbitmq:
    image: rabbitmq:3.7
    container_name: rabbitmq
    ports: ["5672:5672"]
    env_file:
      - worker/.env/common
      - worker/.env/prod.secret

  web:
    # Image
    image: veracioux/web:latest
    build:
      context: .
      dockerfile: Dockerfile.web

    # Container
    container_name: veracioux-web
    depends_on: [db]
    ports: ["8000:8000", "8001:8001"]
    env_file: *env_file
    environment:
      - RABBITMQ_HOST=rabbitmq
      - DB_HOST=db
    volumes:
      - "${HOME}/cert:/cert"

  worker_dotfiles:
    # Image
    image: veracioux/worker_dotfiles:latest
    build:
      context: .
      dockerfile: Dockerfile.worker_dotfiles

    # Container
    container_name: veracioux-worker_dotfiles
    env_file:
      - ./.env/common
      - worker/.env/common
      - worker/.env/prod.secret
    environment: *env_file
