version: '3.4'

services:
  db:
    # Image
    image: postgres:14.1-alpine

    # Container
    container_name: veracioux-db
    ports: ["5432:5432"]
    env_file: &env
      - ./.env/common
      - ./.env/local
      - ./.env/local.secret
      - ./.env/compose
      - worker/.env/common

  rabbitmq:
    image: rabbitmq:3.7
    container_name: rabbitmq
    ports: ["5672:5672"]
    env_file:
      - worker/.env/common

  web:
    # Image
    image: veracioux/web:latest
    build:
      context: .
      dockerfile: Dockerfile.web

    # Container
    container_name: veracioux-web
    depends_on: [db]
    ports: ["5000:5000", "8000:8000", "8001:8001"]
    env_file: *env
    environment:
      - RABBITMQ_HOST=rabbitmq
      - PYTHONDONTWRITEBYTECODE=true

  worker_dotfiles:
    # Image
    image: veracioux/worker_dotfiles:latest
    build:
      context: .
      dockerfile: Dockerfile.worker_dotfiles

    # Container
    container_name: veracioux-worker_dotfiles
    env_file:
      - ./.env/common
      - worker/.env/common
      - worker/.env/local.secret
    environment:
      - RABBITMQ_HOST=rabbitmq
