version: '3.4'

services:
  db:
    # Image
    image: postgres:14.1-alpine

    # Container
    container_name: veracioux-db
    ports: ["5432:5432"]
    env_file:
      - ./.env/env
      - ./.env/local
  web:
    # Image
    image: veracioux/website
    build:
      context: .
      dockerfile: _build/Dockerfile.compose

    # Container
    container_name: veracioux-web
    depends_on: [db]
    ports: ["8000:8000", "8080:8080"]
    env_file:
      - ./.env/env
      - ./.env/local
    volumes:
      - .:/app:rw
