Vagrant.configure("2") do |config|
  config.vm.box = "debian/testing64"
  config.vm.box_check_update = false

  config.vm.disk :disk, size: "10GB", primary: true

  config.vm.disk :disk, size: "50GB", name: "data"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = 2
  end

  config.vm.provision "shell", inline: <<-SHELL
    sudo mkdir -p /etc/nginx/ssl
    sudo install -Dm644 /vagrant/server.dev.crt /etc/nginx/ssl/server.crt
    sudo install -Dm600 /vagrant/server.dev.key /etc/nginx/ssl/server.key
    # Reproduce conditions similar to GCE
    sudo adduser --home /home/haris haris 2>&1 | sed 's/fatal:/warn:/' || true
    sudo echo 'haris ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/haris-passwordless
    sudo chmod 440 /etc/sudoers.d/haris-passwordless
  SHELL

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
  end
end
