Vagrant.configure("2") do |config|
  config.vm.box = "debian/testing64"
  config.vm.box_check_update = false

  config.vm.network "forwarded_port", guest: 80, host: 80
  config.vm.network "forwarded_port", guest: 443, host: 443
  config.vm.network "private_network", ip: "192.168.56.10"

  config.vm.disk :disk, size: "10GB", primary: true

  config.vm.disk :disk, size: "50GB", name: "data"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = 2
  end

 config.vm.provision "shell", inline: <<-SHELL
    # Configuration specific to the local testing VM
    sudo mkdir -p /etc/nginx/ssl
    sudo install -Dm600 /vagrant/dev-certs/* /etc/nginx/ssl/
    # Reproduce conditions similar to GCE
    sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1
    sudo adduser --home /home/haris haris 2>&1 | sed 's/fatal:/warn:/' || true
    sudo echo 'haris ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/haris-passwordless
    sudo chmod 440 /etc/sudoers.d/haris-passwordless
  SHELL

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
  end

  config.vm.provision "shell", inline: <<-SHELL
    sudo cp /home/vagrant/.ssh/authorized_keys ~haris/.ssh/authorized_keys
    sudo chown haris:haris ~haris/.ssh/authorized_keys
    sudo -u haris sed -i 's|REGISTRY_HTTP_HOST:.*|REGISTRY_HTTP_HOST: https://docker.veracioux.local:443|' /home/haris/website/compose.override.yml
    docker-compose --project-directory /home/haris/website up -d
  SHELL
end
