#!/usr/bin/env bash

containers=(veracioux-{web,db,worker_dotfiles,rabbitmq})

if tem var -q env:prod; then
    containers=("${containers[@]}" veracioux-docker-registry)
fi

docker inspect --format '{{.State.Running}}' "${containers[@]}" | grep -qv '^false$'
