#!/usr/bin/env bash

if tem var -q env:prod; then
    containers=("${containers[@]}" veracioux-docker-registry)
    prod="prod"
fi

containers=(veracioux-{web,db,worker,worker_dotfiles,rabbitmq}"$prod")

inspect() {
    docker inspect --format '{{.State.Running}}' "${containers[@]}" 2>/dev/null
}

inspect >/dev/null && inspect | grep -qv '^false$'
