#!/usr/bin/env bash

containers=(veracioux-{web,db,worker_dotfiles,rabbitmq})

if tem var -q env:prod; then
    containers=("${containers[@]}" veracioux-docker-registry)
fi

inspect() {
    docker inspect --format '{{.State.Running}}' "${containers[@]}" 2>/dev/null
}

inspect >/dev/null && inspect | grep -qv '^false$'
