#!/usr/bin/env bash

# Print the contents of the docker-compose.yaml.in file for the given
# environment, after processing it with the template engine. If no argument is
# given, it falls back to the current environment via `tem var env`
#
# Usage:
#   _gen_docker_compose [ENVIRONMENT]

if [ "$#" != 0 ]; then
    env="$1"
else
    env="$(tem var env)"
fi

cd "$(tem find -b website)"

source scripts/load-env.bash.in >/dev/null
cp -f docker-compose.yaml /tmp/veracioux-docker-compose_old.yaml
jinja2 -D env="$env" docker-compose.yaml.in | envsubst > docker-compose.yaml

if ! diff docker-compose.yaml /tmp/veracioux-docker-compose_old.yaml >/dev/null 2>/dev/null
then
    echo "Generated docker-compose.yaml from template."
fi
