#!/usr/bin/env bash

shopt -s globstar

# If this repo had a makefile, this would perform 'make clean'

cd "$(tem find -b website)"
rm -rf _docker
rm docker-compose.*.yaml
rm -rf **/__pycache__

# Remove node_modules/ created in the host by the containers because frontend/
# was shared as a volume in dev mode.
docker run --volume "$PWD:/host:rw" \
    alpine rm -rf /host/{frontend,worker}/node_modules
