#!/usr/bin/env bash

# Generate dockerfiles from shDockerfile

project_root="$(tem find -b website)"

process_types=("$@")

if [ -z "$process_types" ]; then
    process_types=(web worker_dotfiles mail)
fi

for process_type in "${process_types[@]}"; do
    export ENVIRONMENT="$(tem var env)"
    echo "Generating Dockerfile.$process_type.$ENVIRONMENT ..."
    shdocker \
        -s "$project_root/docker/shDockerfile.$process_type" \
        -d "$project_root/Dockerfile.$process_type.$ENVIRONMENT"
done
