#!/usr/bin/env sh

# Clone the project into /tmp/veracioux-website to test the committed changes

cd "$(tem find -b website)"
rm -rf /tmp/veracioux-website
git clone file://"$(pwd)" /tmp/veracioux-website

