#!/usr/bin/env bash

# Generate dockerfiles from shDockerfile

project_root="$(tem find -b veracioux-website)"

process_types=("$@")

if [ -z "$process_types" ]; then
    process_types=(web worker_server worker_dotfiles)
fi

for process_type in "${process_types[@]}"; do
    if tem var -q target:dev; then
        echo "Generating Dockerfile.$process_type.dev ..."
        export ENVIRONMENT=dev
        shdocker \
            -s "$project_root/shDockerfile.$process_type" \
            -d "$project_root/Dockerfile.$process_type.dev"
    else
        export ENVIRONMENT=prod
        echo "Generating Dockerfile.$process_type ..."
        shdocker \
            -s "$project_root/shDockerfile.$process_type" \
            -d "$project_root/Dockerfile.$process_type"
    fi
done
