#!/usr/bin/env bash

cd "$(tem find -b veracioux-website)"

for arg in "$@"; do
    if [ "$arg" = "--help" ] || [ "$arg" = "-h" ]; then
        /usr/bin/docker-compose -f compose-dev.yaml "$@"
        exit
    fi
done

# Generate the necessary dockerfiles
# NOTE: we are generating all dockerfiles every time because some containers
# may have dependencies.
dgen

tem run --no-tem docker-compose -f "$(_get_compose_file)" "$@"

