#!/usr/bin/env bash

cd "$(tem find -b website)"

if ! _all_services_running; then
    up --detach
    VERACIOUX_COMPOSE_NO_GEN=true docker-compose up --detach docker-registry
fi

sudo env PATH="$PATH" USER_HOME="$HOME" scripts/serve.sh

