#!/usr/bin/env bash

export TERM=xterm-256colors

if [ -n "$VPS_IP" ]; then
    host="$VPS_IP"
else
    host="veracioux.me"
fi

if [ "$#" = 0 ]; then
    ssh -t "$host" fish
else
    ssh "$host" "bash -lc \"$(printf '%q ' "$@")\""
fi
