#!/usr/bin/env bash

export TERM=vt100

if [ -n "$VPS_IP" ]; then
    host="$VPS_IP"
else
    host="veracioux.me"
fi

if [ "$#" = 0 ]; then
    ssh "$host"
else
    ssh "$host" "bash -lc \"$(printf '%q ' "$@")\""
fi
