#!/usr/bin/env bash

set -e

if ! tem var -q machine:public; then
    echo "This should only be run on a public-facing server" >&2
    exit 1
fi

curl https://get.acme.sh | sh -s email=me@veracioux.me

mkdir -p ~/cert
cd ~/.acme.sh

./acme.sh --issue -d veracioux.me -d '*.veracioux.me' --dns --yes-I-know-dns-manual-mode-enough-go-ahead-please --debug

read -p "Press any key when you have done that..." -n 1

./acme.sh --renew -d veracioux.me -d '*.veracioux.me' \
    --dns --yes-I-know-dns-manual-mode-enough-go-ahead-please --debug \
    --fullchain-file ~/cert/server.crt
    --key-file       ~/cert/server.key

echo Certificates generated in ~/cert/.
