#!/usr/bin/env bash

# Build and upload the web image to the VPS

cd "$(tem find -b website)"

echo "Building images..."
docker-compose build

curl --fail --insecure "https://veracioux.me/docker-status/"
code="$?"

if [ "$code" != 0 ]; then
    # Docker registry not running
    echo "Registry not running. Pushing manually as tar.gz file..."
    images=(veracioux.me/{web,worker_dotfiles,mail}:latest)
    docker save "${images[@]}" | gzip > /tmp/veracioux-images.tar.gz
    rsync --update --verbose --progress {,"$VPS_IP:"}/tmp/veracioux-images.tar.gz
    ssh "$VPS_IP" bash -c "gunzip /tmp/veracioux-images.tar.gz | docker load"
else
    # TODO
    echo "Pushing images to custom registry..."
    VERACIOUX_COMPOSE_NO_GEN=true docker-compose push
fi

echo "All done."
