#!/usr/bin/env sh

cd "$(tem find -b veracioux-website)"

rsync -v .env/*.secret "$VPS_IP":/home/haris/veracioux-website/.env/
rsync -v worker/.env/*.secret "$VPS_IP":/home/haris/veracioux-website/worker/.env/
rsync -v mail/config.secret.conf "$VPS_IP":/home/haris/veracioux-website/mail/
