#!/usr/bin/env sh

cd "$(tem find -b website)"

rsync -v .env/*.secret "$VPS_IP":/home/haris/website/.env/
rsync -v worker/.env/*.secret "$VPS_IP":/home/haris/website/worker/.env/
rsync -v mail/config.secret.conf "$VPS_IP":/home/haris/website/mail/

connect "mkdir -p ~/auth/"
lpass show docker-registry | connect "htpasswd -Bci ~/auth/htpasswd docker-registry"
