#!/usr/bin/env bash

# Wrapper around docker-compose that generates Dockerfiles from shDockerfiles
# beforehand. You can disable this by setting VERACIOUX_COMPOSE_NO_GEN to a
# non-empty value.

cd "$(tem find -b website)"

has_build_arg=

for arg in "$@"; do
    if [ "$arg" = "--help" ] || [ "$arg" = "-h" ]; then
        tem run --no-tem docker-compose -f nonexistent "$@"
        exit
    elif [ "$arg" = "--build" ] || [ "$arg" = "build" ]; then
        has_build_arg=true
    fi
done

if tem var -q device:public; then
    project_name="veracioux-website-$(tem var env)"
else
    project_name="veracioux-website"
fi

# Generate the necessary Dockerfiles
# NOTE: we are generating all dockerfiles every time because some containers
# may have dependencies.
if [ -z "$VERACIOUX_COMPOSE_NO_GEN" ] && [ -n "$has_build_arg" ]; then
    dgen
fi

_gen_docker_compose

tem run --no-tem docker-compose --project-name "$project_name" -f "$(_find_docker_compose)" "$@"
