#!/usr/bin/env bash

# Force-remove all docker containers related to the website

cd "$(tem find -b website)"

if tem var -q env:prod; then
    read -n 1 -p "You are on production. Proceed? [y/N]: " confirmation
    echo
    if [ "$confirmation" != "y" ] && [ "$confirmation" != "Y" ]; then
        exit 1
    fi
fi

for arg in "$@"; do
    if ! [[ "$arg" == -* ]]; then
        positional_args=("${positional_args[@]}" "$arg")
    fi
    if [ "$arg" = "web" ] && command -v yq >/dev/null; then
        _gen_docker_compose
        positional_args=(
            "${positional_args[@]}"
            $(cat docker-compose.yaml | yq .services.web.depends_on[] --raw-output)
        )
    fi
done

# Documented in our custom `docker-compose` command
# export VERACIOUX_COMPOSE_NO_GEN=true
# TODO: Use hashes to determine if the dockerfiles have changed

docker-compose rm --stop --force "${positional_args[@]}"
