#!/usr/bin/env bash

# Force-remove all docker containers related to the website

cd "$(tem find -b website)"

# Documented in our custom `docker-compose` command
export VERACIOUX_COMPOSE_NO_GEN=true

docker-compose rm -sf "$@"
