#!/usr/bin/env bash

# Start the development containers

cd "$(tem find -b website)"

# Read all positional arguments from the command line (it's a bit heuristic)
positional_args=()
for arg in "$@"; do
    if ! [[ "$arg" == -* ]]; then
        positional_args=("${positional_args[@]}" "$arg")
    fi
done

set -e
down "${positional_args[@]}"
set +e

build='--build'
if tem var -q machine:public; then
    build=''
fi

env="$(tem var env)"

if [ -n "$build" ]; then
    dgen

    # On 'prod' and 'staging', the 'web' service uses frontend as a base image.
    # We have to build it here because docker-compose builds images in parallel
    # and doesn't ensure this dependency is satisfied.
    if [ "$env" != "dev" ]; then
        tem run util/_build_frontend_image
    fi
fi

export VERACIOUX_COMPOSE_NO_GEN=true
docker-compose up $build "$@"

