#!/usr/bin/env bash

# Start the development containers

cd "$(tem find -b veracioux-website)"

positional_args=()

for arg in "$@"; do
    if ! [[ "$arg" == -* ]]; then
        positional_args=("${positional_args[@]}" "$arg")
    fi
done

down "${positional_args[@]}"

build_arg='--build'
if tem var -q env:prod; then
    build_arg=''
fi

docker-compose up $build_arg "$@"

